### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by noreenanwar** [meituan/YOLOv6#181] opened 2022-06-30 21:04 UTC
I am facing this error and I am using customize dataset.I followed the same instructions mentioned by the author.

YOLOv6/yolov6/data/datasets.py", line 337, in get_imgs_labels
    for img_path, info in img_info.items()
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by noreenanwar** [comment] 2022-07-02 00:50
I don't know what is the matter but I am facing this error.I already trained my dataset with yolov5.For yolov6 it very difficult for me to train.

**Comment by Sunzhanxin** [comment] 2022-07-02 08:50
I have also encountered this problem. You just need to replace your data set and tag name with numbers.

**Comment by noreenanwar** [comment] 2022-07-02 13:45
I didn't get your point.what do you mean replace dataset and tags? n with what numbers??

**Comment by cominger** [comment] 2022-07-02 22:16
I face the same problem and the followings are my cases. 
For me, this happens with previously generated .json files (especially **.train.json**)
Now due to the Linux system, we cannot see the file start with "." but os.path.exists found it.
Therefore, I remove the old **.train.json** and also changed the following code.
From yolov6/data/datasets.py:203
 osp.dirname(img_dir), "." + osp.basename(img_dir) + ".json" ->  osp.dirname(img_dir), osp.basename(img_dir) + ".json"

**Comment by noreenanwar** [comment] 2022-07-03 00:08
I changed as you mentioned and I got this error 

YOLOv6/yolov6/data/datasets.py", line 308, in get_imgs_labels
    f"WARNING: No labels found in {osp.dirname(self.img_paths[0])}. "
AttributeError: 'TrainValDataset' object has no attribute 'img_paths'

**Comment by saiteja-kuchipudi** [comment] 2022-07-03 06:58
I was getting the same problem. Fortunately it got resolved. Here is what I did

Step 1: I tried deleting the previous ".train.json" file generated with hashes in it

Step 2: The problem is with images being detected as corrupted, So I have commented the command im.verify() in datasets.py
`    def check_image(im_file):
        # verify an image.
        nc, msg = 0, ""
        try:
            im = Image.open(im_file)
            #im.verify()  # PIL verify`
Step 3: I have modified the image directory folder structure as below
data
--images
-----train (contains training images)
-----val (contains validation images)
-----labels
---------train (contains training annotations)
---------val (contains validation annotations)

**Comment by noreenanwar** [comment] 2022-07-03 12:32
If I follow your steps I got this error.
YOLOv6/yolov6/data/datasets.py", line 422
    nc, msg = 0, ""
    ^
IndentationError: unexpected indent.

plus in lables file your putting json? not txt files?

**Comment by saiteja-kuchipudi** [comment] 2022-07-03 13:12
Labels are in .txt files

**Comment by noreenanwar** [comment] 2022-07-03 13:15
yes But I don't know why I am not able to train my dataset.I have  tried everything

**Comment by M15-3080** [comment] 2022-07-04 00:46
> 是的，但我不知道为什么我无法训练我的数据集。我已经尝试了一切

I suggest you start from scratch, place the train.py file and data set in the root directory, and create a yaml file as follows 
YOLO formatted datasets do not require the Test folder
![image](https://user-images.githubusercontent.com/91411583/177063722-812bf083-991b-4a6a-b716-b32c591f678f.png)
![image](https://user-images.githubusercontent.com/91411583/177063741-2c737556-c828-4e71-ac46-fb511bc9aa78.png)
![image](https://user-images.githubusercontent.com/91411583/177063751-36aa67c8-2d7c-4615-9025-44e40a342aa1.png)

**Comment by noreenanwar** [comment] 2022-07-04 01:31
I got this error again.I have followed your instruction.I think it is not for cityscape dataset.

/YOLOv6/yolov6/data/datasets.py", line 336, in get_imgs_labels
    for img_path, info in img_info.items()
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by noreenanwar** [comment] 2022-07-04 01:39
These error are same I faced earlier.

f"WARNING: No labels found in {osp.dirname(self.img_paths[0])}. "
AttributeError: 'TrainValDataset' object has no attribute 'img_paths'

**Comment by M15-3080** [comment] 2022-07-04 01:49
> 这些错误与我之前遇到的错误相同。
> 
> f“WARNING： 在 {osp.dirname（self.img_paths[0]）} 中找不到任何标签。“ 属性错误： 'TrainValDataset' 对象没有属性 'img_paths'

I have encountered these errors before, but they are all related to the format or path of the dataset. You can test them with other YOLO smaller datasets，Whether it's because of the data set

**Comment by noreenanwar** [comment] 2022-07-04 02:16
Where did you put your labels file?

**Comment by M15-3080** [comment] 2022-07-04 02:20
I'm sorry that my English is not very good. The TXT label file is in the labels folder, and the labels file path is not entered in the YAML file 
![image](https://user-images.githubusercontent.com/91411583/177070444-6cf7e15e-64a6-4cb6-be52-819c789ac561.png)

**Comment by noreenanwar** [comment] 2022-07-04 02:29
<img width="942" alt="Screen Shot 2022-07-03 at 10 27 38 PM" src="https://user-images.githubusercontent.com/52344371/177071020-4dd09f82-e1a0-4f30-9e11-cb17527c4c1b.png">
I have the same directories but still facing issues.I am using cityscape dataset and I also trained it with yolov5 .but for yolov6 I am facing issues.

**Comment by cominger** [comment] 2022-07-04 03:01
I believe you need to make "images" folder for train/val image, as https://github.com/meituan/YOLOv6/issues/181#issuecomment-1173024487 shows in step 3.

**Comment by M15-3080** [comment] 2022-07-04 03:04
> 我相信您需要为火车/val图像创建“图像”文件夹，如步骤3中的[#181（注释）](https://github.com/meituan/YOLOv6/issues/181#issuecomment-1173024487)所示。

No, I didn't create the images folder. If I did, I would get an error that I couldn't find the images

**Comment by saiteja-kuchipudi** [comment] 2022-07-04 10:29
> What is the directory of your labels file?

@noreenanwar Try adding a line anno_path: <path to labels file> in addition to the paths to train and val folders in dataset.yaml file. The variable anno_path has already been embedded in datasets.py

**Comment by ilkin94** [comment] 2022-07-09 01:10
> > 是的，但我不知道为什么我无法训练我的数据集。我已经尝试了一切
> 
> I suggest you start from scratch, place the train.py file and data set in the root directory, and create a yaml file as follows YOLO formatted datasets do not require the Test folder ![image](https://user-images.githubusercontent.com/91411583/177063722-812bf083-991b-4a6a-b716-b32c591f678f.png) ![image](https://user-images.githubusercontent.com/91411583/177063741-2c737556-c828-4e71-ac46-fb511bc9aa78.png) ![image](https://user-images.githubusercontent.com/91411583/177063751-36aa67c8-2d7c-4615-9025-44e40a342aa1.png)

Placing my dataset into YOLOv6 directory solved my problem. Don't place your dataset  outside of main directory (this should be fixed in the future). However, I got another problem, " Unable to find a valid cuDNN algorithm to run convolution" :) I trained my dataset well in YOLOv5 before several times, but, now I get this error.

**Comment by DShaience** [comment] 2022-07-10 08:45
I'm getting this error as well, while trying to use the eval.py with the COCO-Val2017 dataset:
```
    f"WARNING: No labels found in {osp.dirname(self.img_paths[0])}. "
AttributeError: 'TrainValDataset' object has no attribute 'img_paths'
```

I'm unclear how to get the labels/*.txt files? Are they produced from the instances_val2017.json? or some other way? The *.txt files don't exist in the coco dataset

**Comment by DShaience** [comment] 2022-07-10 09:03
Fixed: it was solved by commenting out the logger:
`            # if nf == 0:
            #     LOGGER.warning(
            #         f"WARNING: No labels found in {osp.dirname(self.img_paths[0])}. "
            #     )`
At that point in the code, self.img_paths isn't yet defined. Commenting it out solves it

**Comment by DShaience** [comment] 2022-07-10 09:18
> Labels are in .txt files
@saiteja-kuchipudi  I apologize if this is a basic question - but how should I get/create the labels *.txt files? I'm working with the coco2017 dataset and the txt labels aren't a part of the dataset as far as I've seen

**Comment by saiteja-kuchipudi** [comment] 2022-07-10 10:04
@DShaience I always worked with custom images. But, I hope this [link](https://github.com/amikelive/coco-labels) helps you. Give it a try.

**Closed** 2022-09-20 11:52 UTC
